# Generated by Django 4.2.10 on 2024-08-15 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
    ]
