# Generated by Django 4.2.10 on 2024-09-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date_paid']},
        ),
        migrations.DeleteModel(
            name='Schoolterm',
        ),
    ]
