# Generated by Django 4.2.10 on 2024-10-02 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school_fee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('ADMISSION', 'Admission Fee'), ('TERM', 'Term Fee'), ('ONCE', 'One-time Fee'), ('DAILY', 'Daily Fee')], default='TERM', help_text='Type of fee structure.', max_length=50),
        ),
    ]
