# Generated by Django 4.2.10 on 2024-09-30 12:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('school_fee', '0002_alter_payment_options_delete_schoolterm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fee',
            name='from_date',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='to_date',
        ),
        migrations.AddField(
            model_name='fee',
            name='fee_type',
            field=models.CharField(choices=[('ADMISSION', 'Admission Fee'), ('TERM', 'Term Fee'), ('EXAM', 'Exam Fee'), ('ONCE', 'One-time Fee'), ('DAILY', 'Daily Fee')], default='TERM', help_text='Type of fee structure.', max_length=50),
        ),
        migrations.AddField(
            model_name='fee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='school_fee.school')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='fee',
            name='term',
            field=models.ForeignKey(help_text='Term this fee structure applies to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fees', to='school_fee.term'),
        ),
    ]
