# Generated by Django 4.2.10 on 2024-10-15 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school_fee', '0002_fee_description_alter_fee_fee_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='student',
            unique_together={('name', 'date_of_birth')},
        ),
    ]
