# Generated by Django 4.2.10 on 2024-08-15 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school_fee', '0002_remove_student_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='students',
        ),
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='school_fee.grade'),
        ),
    ]
